import { ReactNode, createContext, useContext, useMemo, useState } from 'react';

export type Language = 'en' | 'de' | 'hu';

const labels = {
  en: '🇬🇧',
  de: '🇩🇪',
  hu: '🇭🇺',
};

const languageNames = {
  en: 'English',
  de: 'Deutsch',
  hu: 'Magyar',
};

const translations = {
  en: {
    navProducts: 'Products',
    navSound: 'Sound Demo',
    navCustomization: 'Customization',
    navShowroom: 'Showroom',
    navContact: 'Contact',
    navQuote: 'Quote',
    heroTitle: 'Space for focus.',
    heroBody:
      'Private acoustic pods that transform open offices into spaces of clarity and concentration.',
    requestQuote: 'Request Quote',
    exploreModels: 'Explore Models',
    trustedBy: 'Trusted by growing teams',
    stickyShowroom: 'Book Showroom',
    quoteTitle: 'Request a quote',
    quoteDescription: 'Get a booth recommendation and price direction within 24h.',
    quotePanelTitle: 'Plan a quieter office.',
    quotePanelBody:
      'Send a few details and we can recommend the right booth size, quantity, and next step.',
    quoteBenefitPrice: 'Get price direction in 24h',
    quoteBenefitAssessment: 'Free office noise assessment',
    quoteBenefitSlots: 'Showroom slots available this week',
    quoteBenefitLeasing: 'Leasing options available',
    name: 'Name',
    company: 'Company',
    email: 'Email',
    phone: 'Phone',
    city: 'City',
    boothNeed: 'Booth need',
    notesPlaceholder: 'What should we know about your office?',
    sendRequest: 'Send request',
    notSure: 'Not sure yet',
    multipleBooths: 'Multiple booths',
    productsTitle: 'Choose your space.',
    productsBody:
      'From solo focus to team meetings, we have the right solution for every privacy need.',
    getPrice: 'Get price in 24h',
    soundTitle: 'Experience the difference.',
    soundBody: 'Toggle between a typical open office and a Silent Box booth.',
    soundHint: 'Click to play the real sound comparison.',
    openDoor: 'Open door 85 dB',
    closedDoor: 'Closed door 30 dB',
    stopSound: 'Stop sound',
    openDoorLabel: 'Open door',
    closedDoorLabel: 'Closed door',
    office85: 'Office sound reaches 85 dB',
    silent30: 'Silent Box drops to 30 dB',
    noisyDesc:
      'Constant chatter, keyboard clicks, phone calls, and background music create a distracting environment.',
    silentDesc: 'Precision-engineered acoustic panels reduce external noise to library-quiet levels.',
    showroomDemo: 'Real showroom demo',
    hearShowroom: 'Hear this in our showroom.',
    bringDemo:
      'Bring your own call, laptop, or team member and compare open-office noise with a closed Silent Box.',
    bookSoundDemo: 'Book a sound demo',
    planFaster: 'Plan faster',
    salesTitle: 'Find the right booth before you talk to sales.',
    freeAssessment: 'Free office noise assessment',
    findBooth: 'Find your booth',
    recommendedFor: 'Recommended for',
    employeeCalculator: 'Employee calculator',
    employeeQuestion: 'How many employees use the office?',
    startingPlan: 'Starting plan',
    finalQuantity:
      'Final quantity depends on meeting habits, floor layout, and hybrid work patterns.',
    compareOptions: 'Compare your options',
    compareBody: 'Silent Box keeps the privacy benefits without a renovation project.',
    lowerFriction: 'Lower purchase friction',
    buyerResources: 'Buyer resources',
    buyerTitle: 'Get the booth buyer guide and spec sheet.',
    buyerBody:
      'Useful for facility managers, architects, and teams comparing acoustic options.',
    getSpecSheet: 'Get spec sheet',
    architectPack: 'Architect pack',
    showroomTitle: 'Experience silence in person.',
    showroomBody: 'Visit our showrooms to see, feel, and hear the difference yourself.',
    bookVisit: 'Book Visit',
    virtualTitle: "Can't visit in person?",
    virtualBody: 'Schedule a virtual consultation with our space planning experts.',
    virtualTour: 'Schedule Virtual Tour',
    finalTitle: "Let's create quieter workspaces.",
    finalBody:
      'Transform your office into a space where focus, privacy, and productivity thrive.',
    getStarted: 'Get Started',
    downloadBrochure: 'Download Brochure',
    productMatterhornTagline: 'Personal focus pod',
    productKilimanjaroTagline: 'Private collaboration',
    productEverestTagline: 'Team conference room',
    priceMatterhorn: 'From €6,999',
    priceKilimanjaro: 'From €9,999',
    priceEverest: 'From €14,999',
    productMatterhornFeature1: 'Phone booth footprint',
    productMatterhornFeature2: 'Ideal for calls',
    productMatterhornFeature3: 'Individual focus work',
    productKilimanjaroFeature1: 'Two-person meetings',
    productKilimanjaroFeature2: 'Video calls',
    productKilimanjaroFeature3: 'Private interviews',
    productEverestFeature1: 'Team meetings',
    productEverestFeature2: 'Client presentations',
    productEverestFeature3: 'Small group sessions',
    problemTitle: 'The cost of noise.',
    problemBody:
      'Open offices help people connect, but they make focus fragile. Calls spill into desk areas, meeting rooms stay booked, and every interruption costs time.',
    problemBusyAlt: 'Busy open office',
    problemSilentAlt: 'Silent Box booth',
    problemStat1: 'report frequent distractions',
    problemStat2: 'lack private meeting space',
    problemStat3: 'to regain focus after an interruption',
    customerFitTitle: 'Built for every stakeholder.',
    customerFitBody:
      'Different teams buy privacy for different reasons. Atlasz Silent Boxes give facilities, finance, HR, and daily users one practical answer.',
    cfFacilityTitle: 'Facility managers',
    cfFacilityNeed: 'Add privacy capacity without construction work.',
    cfFacilityProof: 'Modular installation, predictable footprint, serviceable components.',
    cfHrTitle: 'HR and people teams',
    cfHrNeed: 'Create calmer shared offices with fewer distractions.',
    cfHrProof: 'Private calls, reset spaces, focus zones, and neurodiverse-friendly use.',
    cfFinanceTitle: 'Finance and leadership',
    cfFinanceNeed: 'Choose a measurable alternative to building more meeting rooms.',
    cfFinanceProof: 'Lower disruption, scalable rollout, and clearer utilization.',
    cfLegalTitle: 'Legal, healthcare and advisors',
    cfLegalNeed: 'Protect confidential conversations in shared workspaces.',
    cfLegalProof: 'Acoustic reduction, visual privacy options, and secure meeting use cases.',
    cfTeamsTitle: 'Teams and operators',
    cfTeamsNeed: 'Give people reliable rooms for calls, interviews, deep work, and quick syncs.',
    cfTeamsProof: 'Matterhorn, Kilimanjaro, and Everest sizes cover daily office workflows.',
    cfCoworkingTitle: 'Coworking spaces',
    cfCoworkingNeed: 'Offer premium rentable privacy that improves member experience.',
    cfCoworkingProof: 'Bookable pods, durable finishes, and easy placement across floorplans.',
    featureAcousticTitle: 'Acoustic comfort',
    featureAcoustic1: 'Layered sound absorption',
    featureAcoustic2: 'Reduced speech distraction',
    featureAcoustic3: 'Calmer interior feel',
    featureOpsTitle: 'Operational fit',
    featureOps1: 'No major construction',
    featureOps2: 'Moveable when teams change',
    featureOps3: 'Easy maintenance access',
    featureQualityTitle: 'Workplace quality',
    featureQuality1: 'Ventilation and lighting',
    featureQuality2: 'Power for focused sessions',
    featureQuality3: 'Materials for premium offices',
    useCasesTitle: 'Everyday reasons people need a booth.',
    useCasesBody: 'One product solves many small workplace frictions.',
    useCase1: 'Private sales calls',
    useCase2: 'Recruitment interviews',
    useCase3: 'Therapy or consultation calls',
    useCase4: 'Legal and finance discussions',
    useCase5: 'Deep work sprints',
    useCase6: 'Podcast or webinar recording',
    useCase7: 'Hybrid team meetings',
    useCase8: 'Quiet recovery moments',
    interactiveTitle: 'Designed for performance.',
    interactiveBody: 'Explore the details that make each booth comfortable, quiet, and easy to use every day.',
    hotspotHint: 'Hover over the hotspots to explore features',
    hotspotVentTitle: 'Smart ventilation',
    hotspotVentDesc: 'Fresh air circulation with CO2-aware controls.',
    hotspotSoundTitle: 'Sound insulation',
    hotspotSoundDesc: '30 dB acoustic reduction with layered materials.',
    hotspotLightTitle: 'LED lighting',
    hotspotLightDesc: 'Adjustable color temperature for calls and focus work.',
    hotspotSeatTitle: 'Ergonomic seating',
    hotspotSeatDesc: 'Comfortable seating for longer sessions.',
    hotspotSensorsTitle: 'Smart sensors',
    hotspotSensorsDesc: 'Occupancy and usage data for better planning.',
    hotspotPowerTitle: 'Power outlets',
    hotspotPowerDesc: 'USB-C, wireless charging, and standard sockets.',
    hotspotEcoTitle: 'Responsible materials',
    hotspotEcoDesc: 'Durable finishes with a lower-impact material mix.',
    customizationTitle: 'Design your space.',
    customizationBody: 'Match the booth to your office palette, material standards, and daily use.',
    colorLabel: 'Color',
    materialLabel: 'Material',
    sizeLabel: 'Size',
    selectedLabel: 'Selected',
    customQuote: 'Get Custom Quote',
    yourConfiguration: 'Your Configuration',
    livePreview: 'Live Preview',
    colorCharcoal: 'Charcoal',
    colorSage: 'Sage',
    colorWarmWhite: 'Warm White',
    colorWood: 'Wood',
    colorGraphite: 'Graphite',
    materialOak: 'Oak veneer',
    materialOakFinish: 'Natural wood',
    materialFelt: 'Felt panel',
    materialFeltFinish: 'Acoustic fabric',
    materialPowder: 'Powder coat',
    materialPowderFinish: 'Matte metal',
    materialGlass: 'Glass',
    materialGlassFinish: 'Frosted',
    environmentTitle: 'Trusted across industries.',
    environmentBody: 'From confidential advisors to high-growth teams, Atlasz Silent Boxes adapt to the way people work.',
    envLawTitle: 'Law firms',
    envLawDesc: 'Confidential client calls inside open offices',
    envTechTitle: 'Tech teams',
    envTechDesc: 'Focus rooms for energetic product teams',
    envCoworkTitle: 'Coworking spaces',
    envCoworkDesc: 'Bookable privacy in shared workplaces',
    envHealthTitle: 'Healthcare',
    envHealthDesc: 'Private consultation areas for sensitive conversations',
    envEnterpriseTitle: 'Enterprise offices',
    envEnterpriseDesc: 'Scalable privacy for large teams and multiple floors',
    envArchTitle: 'Architecture studios',
    envArchDesc: 'Acoustic rooms that respect designed interiors',
    caseStudies: 'Get case studies',
    techTitle: 'Engineering that works quietly.',
    techBody: 'Every booth combines acoustic performance, comfort systems, and materials chosen for daily commercial use.',
    techAcousticTitle: 'Acoustic engineering',
    techAcousticDesc: 'Multi-layer sound absorption with precision-built panels.',
    techVentTitle: 'Ventilation system',
    techVentDesc: 'Quiet air circulation with smart adjustment.',
    techPowerTitle: 'Power and connectivity',
    techPowerDesc: 'Integrated charging and cable management.',
    techClimateTitle: 'Climate comfort',
    techClimateDesc: 'Stable comfort for longer sessions.',
    techSustainTitle: 'Responsible materials',
    techSustainDesc: 'Lower-impact construction with certified sources.',
    techAnalyticsTitle: 'Smart analytics',
    techAnalyticsDesc: 'Usage insights for better workplace planning.',
    specReduction: '30 dB reduction',
    specAbsorption: 'Full-spectrum absorption',
    specEcho: 'Echo control',
    specFans: 'Quiet fans',
    specFreshAir: 'Fresh air circulation',
    specSensors: 'Smart sensors',
    specUsb: 'USB-C power',
    specWireless: 'Wireless charging',
    specCable: 'Cable ports',
    specCooling: 'Active cooling',
    specHeat: 'Heat dissipation',
    specHumidity: 'Humidity control',
    specRecycled: '80% recycled content',
    specVoc: 'Low VOC',
    specCarbon: 'Lower-carbon options',
    specOccupancy: 'Occupancy detection',
    specPatterns: 'Usage patterns',
    specMaintenance: 'Maintenance alerts',
    statYears: 'Years R&D',
    statPatents: 'Patents',
    statUptime: 'Uptime',
    statWarranty: 'Warranty',
    testimonialsTitle: 'Loved by teams worldwide.',
    testimonialsBody: 'Teams choose Atlasz Silent Boxes when focus, privacy, and fast installation all matter.',
    testQuote1: 'Our open office became much easier to work in. The quiet rooms were used from day one.',
    testQuote2: 'Client confidentiality is non-negotiable. The booths gave our team private space without a rebuild.',
    testQuote3: 'The booth feels like part of the interior, not a temporary office fix.',
    testQuote4: 'Installation was clean and fast. We avoided the disruption of construction.',
    testQuote5: 'I can finally take deep-work sessions without hunting for an empty meeting room.',
    testQuote6: 'The business case was easy: fewer interruptions, better calls, and faster rollout.',
    roleOps: 'Head of Operations',
    rolePartner: 'Managing Partner',
    roleDesign: 'Design Director',
    roleFacilities: 'Facilities Manager',
    roleEngineer: 'Senior Engineer',
    roleCoo: 'COO',
    avgRating: 'Average rating',
    companies: 'Companies',
    boothsInstalled: 'Booths installed',
    contactEmail: 'Email us',
    contactPhone: 'Call us',
    contactChat: 'Live chat',
    chatHours: 'Available 9-6',
    footerTagline: 'Premium acoustic office solutions.',
    footerProducts: 'Products',
    footerFeatures: 'Features',
    footerPricing: 'Pricing',
    footerCustomization: 'Customization',
    footerCompany: 'Company',
    footerAbout: 'About',
    footerCareers: 'Careers',
    footerPress: 'Press',
    footerSupport: 'Support',
    footerContact: 'Contact',
    footerFaq: 'FAQ',
    footerWarranty: 'Warranty',
    footerRights: 'All rights reserved.',
    footerPrivacy: 'Privacy',
    footerTerms: 'Terms',
    footerCookies: 'Cookies',
    soundSealed: 'sealed',
    soundLeaking: 'leaking',
    noiseReduction: 'Noise reduction',
    soundAbsorption: 'Sound absorption',
    insideBooth: 'Inside booth',
    boothSoloTitle: 'Calls and deep focus',
    boothSoloDesc: 'For phone calls, video meetings, and one-person work that needs quiet.',
    boothDuoTitle: '1-on-1 meetings',
    boothDuoDesc: 'For hiring, manager check-ins, pair work, and private conversations.',
    boothMeetTitle: 'Team calls',
    boothMeetDesc: 'For small teams, client presentations, and recurring group meetings.',
    recSmall: '1 Matterhorn + 1 Kilimanjaro',
    recMedium: '2 Matterhorn + 1 Kilimanjaro + 1 Everest',
    recLarge: '4 Matterhorn + 2 Kilimanjaro + 2 Everest',
    recCustom: 'Custom multi-zone plan',
    compareNeed: 'Need',
    compareSilent: 'Silent Box',
    compareMeeting: 'Meeting room',
    compareHeadphones: 'Headphones',
    compareRenovation: 'Renovation',
    compareTime: 'Time to use',
    compareFast: 'Fast install',
    compareProject: 'Construction project',
    compareImmediate: 'Immediate',
    compareWeeks: 'Weeks of work',
    comparePrivacy: 'Privacy',
    compareHigh: 'High',
    compareMedium: 'Medium',
    compareLow: 'Low',
    compareFlex: 'Flexibility',
    compareRelocatable: 'Relocatable',
    compareFixedRoom: 'Fixed room',
    compareIndividual: 'Individual only',
    compareFixedLayout: 'Fixed layout',
    compareDisruption: 'Office disruption',
    frictionInstallTitle: 'Installation',
    frictionInstallDesc: 'Installed in hours, no construction work.',
    frictionWarrantyTitle: 'Warranty',
    frictionWarrantyDesc: 'Coverage and local service support included.',
    frictionDeliveryTitle: 'Delivery',
    frictionDeliveryDesc: 'Clear lead times before order approval.',
    frictionFinanceTitle: 'Financing',
    frictionFinanceDesc: 'Leasing options for monthly budgets.',
    proofOpenTitle: 'Open-plan team floor',
    proofOpenResult: '3 Matterhorn booths moved call noise away from the main desk area.',
    proofStudioTitle: 'Client-facing studio',
    proofStudioResult: 'Kilimanjaro gave managers a private room without waiting for construction.',
    proofOpsTitle: 'Growing operations office',
    proofOpsResult: 'Everest created a dedicated video-call space near the team.',
    customizedBoothAlt: 'Customized booth preview',
    monFri96: 'Mon-Fri 9-6',
    monFri107: 'Mon-Fri 10-7',
  },
  de: {
    navProducts: 'Produkte',
    navSound: 'Sound-Demo',
    navCustomization: 'Anpassung',
    navShowroom: 'Showroom',
    navContact: 'Kontakt',
    navQuote: 'Angebot',
    heroTitle: 'Raum für Fokus.',
    heroBody:
      'Private Akustik-Pods verwandeln offene Büros in Räume für Klarheit und Konzentration.',
    requestQuote: 'Angebot anfragen',
    exploreModels: 'Modelle ansehen',
    trustedBy: 'Vertraut von wachsenden Teams',
    stickyShowroom: 'Showroom buchen',
    quoteTitle: 'Angebot anfragen',
    quoteDescription: 'Erhalten Sie eine Booth-Empfehlung und Preisrichtung innerhalb von 24h.',
    quotePanelTitle: 'Planen Sie ein ruhigeres Büro.',
    quotePanelBody:
      'Senden Sie uns ein paar Details, und wir empfehlen Größe, Anzahl und nächsten Schritt.',
    quoteBenefitPrice: 'Preisrichtung in 24h',
    quoteBenefitAssessment: 'Kostenlose Büro-Lärmanalyse',
    quoteBenefitSlots: 'Showroom-Termine diese Woche',
    quoteBenefitLeasing: 'Leasingoptionen verfügbar',
    name: 'Name',
    company: 'Firma',
    email: 'E-Mail',
    phone: 'Telefon',
    city: 'Stadt',
    boothNeed: 'Booth-Bedarf',
    notesPlaceholder: 'Was sollten wir über Ihr Büro wissen?',
    sendRequest: 'Anfrage senden',
    notSure: 'Noch nicht sicher',
    multipleBooths: 'Mehrere Booths',
    productsTitle: 'Wählen Sie Ihren Raum.',
    productsBody:
      'Von Einzel-Fokus bis Teammeeting: die passende Lösung für jede Privatsphäre.',
    getPrice: 'Preis in 24h erhalten',
    soundTitle: 'Erleben Sie den Unterschied.',
    soundBody: 'Wechseln Sie zwischen offenem Büro und Silent Box Booth.',
    soundHint: 'Klicken Sie, um den echten Klangvergleich zu hören.',
    openDoor: 'Offene Tür 85 dB',
    closedDoor: 'Geschlossene Tür 30 dB',
    stopSound: 'Sound stoppen',
    openDoorLabel: 'Offene Tür',
    closedDoorLabel: 'Geschlossene Tür',
    office85: 'Bürogeräusche erreichen 85 dB',
    silent30: 'Silent Box reduziert auf 30 dB',
    noisyDesc:
      'Gespräche, Tastaturen, Telefonate und Musik schaffen eine ablenkende Umgebung.',
    silentDesc: 'Präzise Akustikpaneele senken Außengeräusche auf Bibliotheksniveau.',
    showroomDemo: 'Echte Showroom-Demo',
    hearShowroom: 'Hören Sie es in unserem Showroom.',
    bringDemo:
      'Bringen Sie Ihren eigenen Anruf, Laptop oder Kollegen mit und vergleichen Sie selbst.',
    bookSoundDemo: 'Sound-Demo buchen',
    planFaster: 'Schneller planen',
    salesTitle: 'Finden Sie die richtige Booth, bevor Sie mit Sales sprechen.',
    freeAssessment: 'Kostenlose Büro-Lärmanalyse',
    findBooth: 'Ihre Booth finden',
    recommendedFor: 'Empfohlen für',
    employeeCalculator: 'Mitarbeiter-Rechner',
    employeeQuestion: 'Wie viele Mitarbeitende nutzen das Büro?',
    startingPlan: 'Startplan',
    finalQuantity:
      'Die finale Anzahl hängt von Meetings, Grundriss und Hybridarbeit ab.',
    compareOptions: 'Optionen vergleichen',
    compareBody: 'Silent Box bietet Privatsphäre ohne Renovierungsprojekt.',
    lowerFriction: 'Einfacher entscheiden',
    buyerResources: 'Käufer-Ressourcen',
    buyerTitle: 'Erhalten Sie Buyer Guide und Spec Sheet.',
    buyerBody: 'Nützlich für Facility Manager, Architekten und vergleichende Teams.',
    getSpecSheet: 'Spec Sheet erhalten',
    architectPack: 'Architektenpaket',
    showroomTitle: 'Erleben Sie Stille persönlich.',
    showroomBody: 'Besuchen Sie unsere Showrooms und hören Sie den Unterschied selbst.',
    bookVisit: 'Besuch buchen',
    virtualTitle: 'Kein persönlicher Besuch möglich?',
    virtualBody: 'Planen Sie eine virtuelle Beratung mit unseren Raumexperten.',
    virtualTour: 'Virtuelle Tour planen',
    finalTitle: 'Schaffen wir ruhigere Arbeitsplätze.',
    finalBody:
      'Verwandeln Sie Ihr Büro in einen Ort für Fokus, Privatsphäre und Produktivität.',
    getStarted: 'Starten',
    downloadBrochure: 'Broschüre herunterladen',
    productMatterhornTagline: 'Ruhiger Fokusraum für eine Person',
    productKilimanjaroTagline: 'Privater Raum für Zusammenarbeit',
    productEverestTagline: 'Kompakter Team-Meetingraum',
    priceMatterhorn: 'Ab €6.999',
    priceKilimanjaro: 'Ab €9.999',
    priceEverest: 'Ab €14.999',
    productMatterhornFeature1: 'Kleine Telefonbox-Fläche',
    productMatterhornFeature2: 'Ideal für Anrufe',
    productMatterhornFeature3: 'Konzentriertes Einzelarbeiten',
    productKilimanjaroFeature1: 'Meetings zu zweit',
    productKilimanjaroFeature2: 'Videocalls',
    productKilimanjaroFeature3: 'Diskrete Interviews',
    productEverestFeature1: 'Teammeetings',
    productEverestFeature2: 'Kundenpräsentationen',
    productEverestFeature3: 'Sessions in kleinen Gruppen',
    problemTitle: 'Was Lärm wirklich kostet.',
    problemBody:
      'Offene Büros fördern Austausch, machen Konzentration aber empfindlich. Gespräche landen am Arbeitsplatz, Meetingräume sind belegt, und jede Unterbrechung kostet Zeit.',
    problemBusyAlt: 'Unruhiges Großraumbüro',
    problemSilentAlt: 'Silent Box Akustikkabine',
    problemStat1: 'berichten von häufigen Ablenkungen',
    problemStat2: 'haben zu wenig private Meetingflächen',
    problemStat3: 'bis der Fokus nach einer Unterbrechung zurückkehrt',
    customerFitTitle: 'Gebaut für alle, die mitentscheiden.',
    customerFitBody:
      'Jede Abteilung kauft Ruhe aus einem anderen Grund. Atlasz Silent Boxes geben Facility, Finance, HR und Nutzern eine gemeinsame, praktische Lösung.',
    cfFacilityTitle: 'Facility Manager',
    cfFacilityNeed: 'Mehr Privatsphäre schaffen, ohne Bauprojekt.',
    cfFacilityProof: 'Modulare Installation, planbare Stellfläche, wartbare Komponenten.',
    cfHrTitle: 'HR- und People-Teams',
    cfHrNeed: 'Ruhigere Gemeinschaftsbüros mit weniger Ablenkung schaffen.',
    cfHrProof: 'Private Calls, Rückzugsorte, Fokuszonen und neurodiversitätsfreundliche Nutzung.',
    cfFinanceTitle: 'Finance und Geschäftsführung',
    cfFinanceNeed: 'Eine messbare Alternative zu neuen Meetingräumen wählen.',
    cfFinanceProof: 'Weniger Störung, skalierbarer Rollout und klarere Nutzung.',
    cfLegalTitle: 'Recht, Gesundheit und Beratung',
    cfLegalNeed: 'Vertrauliche Gespräche in geteilten Arbeitsbereichen schützen.',
    cfLegalProof: 'Akustische Reduktion, Sichtschutzoptionen und sichere Meeting-Szenarien.',
    cfTeamsTitle: 'Teams und Operations',
    cfTeamsNeed: 'Verlässliche Räume für Calls, Interviews, Deep Work und kurze Abstimmungen.',
    cfTeamsProof: 'Matterhorn, Kilimanjaro und Everest decken typische Büroabläufe ab.',
    cfCoworkingTitle: 'Coworking Spaces',
    cfCoworkingNeed: 'Hochwertige, buchbare Privatsphäre anbieten, die Mitglieder spüren.',
    cfCoworkingProof: 'Buchbare Pods, robuste Oberflächen und einfache Platzierung im Grundriss.',
    featureAcousticTitle: 'Akustischer Komfort',
    featureAcoustic1: 'Mehrschichtige Schallabsorption',
    featureAcoustic2: 'Weniger Sprachablenkung',
    featureAcoustic3: 'Ruhigeres Innengefühl',
    featureOpsTitle: 'Passt in den Betrieb',
    featureOps1: 'Keine große Baustelle',
    featureOps2: 'Umstellbar, wenn Teams wachsen',
    featureOps3: 'Einfacher Wartungszugang',
    featureQualityTitle: 'Qualität im Alltag',
    featureQuality1: 'Lüftung und Licht',
    featureQuality2: 'Strom für konzentrierte Sessions',
    featureQuality3: 'Materialien für hochwertige Büros',
    useCasesTitle: 'Alltägliche Gründe für eine Kabine.',
    useCasesBody: 'Ein Produkt löst viele kleine Reibungen im Büroalltag.',
    useCase1: 'Private Vertriebscalls',
    useCase2: 'Recruiting-Interviews',
    useCase3: 'Therapie- oder Beratungsgespräche',
    useCase4: 'Rechts- und Finanzgespräche',
    useCase5: 'Deep-Work-Sprints',
    useCase6: 'Podcast- oder Webinar-Aufnahmen',
    useCase7: 'Hybride Teammeetings',
    useCase8: 'Kurze ruhige Erholung',
    interactiveTitle: 'Für Leistung im Alltag entwickelt.',
    interactiveBody: 'Entdecken Sie die Details, die jede Kabine komfortabel, leise und leicht nutzbar machen.',
    hotspotHint: 'Bewegen Sie den Cursor über die Punkte, um Funktionen zu entdecken',
    hotspotVentTitle: 'Smarte Lüftung',
    hotspotVentDesc: 'Frischluftzufuhr mit CO2-bewusster Steuerung.',
    hotspotSoundTitle: 'Schalldämmung',
    hotspotSoundDesc: '30 dB akustische Reduktion durch mehrschichtige Materialien.',
    hotspotLightTitle: 'LED-Beleuchtung',
    hotspotLightDesc: 'Anpassbare Farbtemperatur für Calls und Fokusarbeit.',
    hotspotSeatTitle: 'Ergonomisches Sitzen',
    hotspotSeatDesc: 'Komfortables Sitzen auch für längere Sessions.',
    hotspotSensorsTitle: 'Smarte Sensoren',
    hotspotSensorsDesc: 'Belegungs- und Nutzungsdaten für bessere Planung.',
    hotspotPowerTitle: 'Stromanschlüsse',
    hotspotPowerDesc: 'USB-C, kabelloses Laden und Standardsteckdosen.',
    hotspotEcoTitle: 'Verantwortungsvolle Materialien',
    hotspotEcoDesc: 'Robuste Oberflächen mit materialschonenderem Mix.',
    customizationTitle: 'Gestalten Sie Ihren Raum.',
    customizationBody: 'Passen Sie die Kabine an Farbwelt, Materialstandard und Nutzung Ihres Büros an.',
    colorLabel: 'Farbe',
    materialLabel: 'Material',
    sizeLabel: 'Größe',
    selectedLabel: 'Ausgewählt',
    customQuote: 'Individuelles Angebot anfragen',
    yourConfiguration: 'Ihre Konfiguration',
    livePreview: 'Live-Vorschau',
    colorCharcoal: 'Anthrazit',
    colorSage: 'Salbeigrün',
    colorWarmWhite: 'Warmweiß',
    colorWood: 'Holz',
    colorGraphite: 'Graphit',
    materialOak: 'Eichenfurnier',
    materialOakFinish: 'Natürliches Holz',
    materialFelt: 'Filzpaneel',
    materialFeltFinish: 'Akustikstoff',
    materialPowder: 'Pulverbeschichtung',
    materialPowderFinish: 'Mattes Metall',
    materialGlass: 'Glas',
    materialGlassFinish: 'Satiniert',
    environmentTitle: 'Bewährt in vielen Branchen.',
    environmentBody: 'Von vertraulichen Beratungen bis zu schnell wachsenden Teams: Atlasz Silent Boxes passen sich der Arbeit an.',
    envLawTitle: 'Kanzleien',
    envLawDesc: 'Vertrauliche Mandantengespräche im offenen Büro',
    envTechTitle: 'Tech-Teams',
    envTechDesc: 'Fokusräume für dynamische Produktteams',
    envCoworkTitle: 'Coworking Spaces',
    envCoworkDesc: 'Buchbare Privatsphäre in geteilten Arbeitswelten',
    envHealthTitle: 'Gesundheitswesen',
    envHealthDesc: 'Private Beratungsbereiche für sensible Gespräche',
    envEnterpriseTitle: 'Enterprise-Büros',
    envEnterpriseDesc: 'Skalierbare Privatsphäre für große Teams und mehrere Etagen',
    envArchTitle: 'Architekturbüros',
    envArchDesc: 'Akustische Räume, die gestaltete Interiors respektieren',
    caseStudies: 'Case Studies anfordern',
    techTitle: 'Technik, die leise arbeitet.',
    techBody: 'Jede Kabine verbindet Akustik, Komfortsysteme und Materialien für den täglichen Einsatz im Büro.',
    techAcousticTitle: 'Akustik-Engineering',
    techAcousticDesc: 'Mehrschichtige Schallabsorption mit präzise gefertigten Paneelen.',
    techVentTitle: 'Lüftungssystem',
    techVentDesc: 'Leise Luftzirkulation mit smarter Anpassung.',
    techPowerTitle: 'Strom und Konnektivität',
    techPowerDesc: 'Integriertes Laden und sauberes Kabelmanagement.',
    techClimateTitle: 'Klimakomfort',
    techClimateDesc: 'Stabile Behaglichkeit für längere Sessions.',
    techSustainTitle: 'Verantwortungsvolle Materialien',
    techSustainDesc: 'Materialien mit geringerer Wirkung und zertifizierten Quellen.',
    techAnalyticsTitle: 'Smarte Analysen',
    techAnalyticsDesc: 'Nutzungsdaten für bessere Arbeitsplatzplanung.',
    specReduction: '30 dB Reduktion',
    specAbsorption: 'Breitbandige Absorption',
    specEcho: 'Echo-Kontrolle',
    specFans: 'Leise Ventilatoren',
    specFreshAir: 'Frischluftzirkulation',
    specSensors: 'Smarte Sensoren',
    specUsb: 'USB-C Strom',
    specWireless: 'Kabelloses Laden',
    specCable: 'Kabeldurchführungen',
    specCooling: 'Aktive Kühlung',
    specHeat: 'Wärmeableitung',
    specHumidity: 'Feuchtigkeitskontrolle',
    specRecycled: '80% Recyclinganteil',
    specVoc: 'Niedrige VOC-Werte',
    specCarbon: 'CO2-ärmere Optionen',
    specOccupancy: 'Belegungserkennung',
    specPatterns: 'Nutzungsmuster',
    specMaintenance: 'Wartungshinweise',
    statYears: 'Jahre F&E',
    statPatents: 'Patente',
    statUptime: 'Verfügbarkeit',
    statWarranty: 'Garantie',
    testimonialsTitle: 'Von Teams weltweit geschätzt.',
    testimonialsBody: 'Teams wählen Atlasz Silent Boxes, wenn Fokus, Privatsphäre und schnelle Installation zusammen zählen.',
    testQuote1: 'Unser offenes Büro wurde sofort leichter nutzbar. Die ruhigen Räume waren vom ersten Tag an belegt.',
    testQuote2: 'Mandantenvertraulichkeit ist unverhandelbar. Die Kabinen gaben uns Privatsphäre ohne Umbau.',
    testQuote3: 'Die Kabine wirkt wie Teil des Interiors, nicht wie eine provisorische Bürolösung.',
    testQuote4: 'Die Installation war sauber und schnell. Wir haben uns eine Baustelle erspart.',
    testQuote5: 'Ich kann endlich Deep Work machen, ohne nach freien Meetingräumen zu suchen.',
    testQuote6: 'Der Business Case war klar: weniger Unterbrechungen, bessere Calls, schneller Rollout.',
    roleOps: 'Leitung Operations',
    rolePartner: 'Managing Partner',
    roleDesign: 'Design Director',
    roleFacilities: 'Facility Manager',
    roleEngineer: 'Senior Engineer',
    roleCoo: 'COO',
    avgRating: 'Durchschnittliche Bewertung',
    companies: 'Unternehmen',
    boothsInstalled: 'Installierte Kabinen',
    contactEmail: 'E-Mail',
    contactPhone: 'Anrufen',
    contactChat: 'Live-Chat',
    chatHours: 'Verfügbar 9-18 Uhr',
    footerTagline: 'Premium-Akustiklösungen für Büros.',
    footerProducts: 'Produkte',
    footerFeatures: 'Funktionen',
    footerPricing: 'Preise',
    footerCustomization: 'Anpassung',
    footerCompany: 'Unternehmen',
    footerAbout: 'Über uns',
    footerCareers: 'Karriere',
    footerPress: 'Presse',
    footerSupport: 'Support',
    footerContact: 'Kontakt',
    footerFaq: 'FAQ',
    footerWarranty: 'Garantie',
    footerRights: 'Alle Rechte vorbehalten.',
    footerPrivacy: 'Datenschutz',
    footerTerms: 'AGB',
    footerCookies: 'Cookies',
    soundSealed: 'geschlossen',
    soundLeaking: 'Schall tritt aus',
    noiseReduction: 'Geräuschreduktion',
    soundAbsorption: 'Schallabsorption',
    insideBooth: 'Innen in der Kabine',
    boothSoloTitle: 'Calls und Deep Work',
    boothSoloDesc: 'Für Telefonate, Videomeetings und konzentriertes Arbeiten allein.',
    boothDuoTitle: '1:1-Meetings',
    boothDuoDesc: 'Für Bewerbungsgespräche, Check-ins und vertrauliche Gespräche.',
    boothMeetTitle: 'Team-Calls',
    boothMeetDesc: 'Für kleine Teams, Kundenpräsentationen und wiederkehrende Meetings.',
    recSmall: '1 Matterhorn + 1 Kilimanjaro',
    recMedium: '2 Matterhorn + 1 Kilimanjaro + 1 Everest',
    recLarge: '4 Matterhorn + 2 Kilimanjaro + 2 Everest',
    recCustom: 'Individueller Mehrzonen-Plan',
    compareNeed: 'Anforderung',
    compareSilent: 'Silent Box',
    compareMeeting: 'Meetingraum',
    compareHeadphones: 'Kopfhörer',
    compareRenovation: 'Umbau',
    compareTime: 'Zeit bis zur Nutzung',
    compareFast: 'Schnelle Installation',
    compareProject: 'Bauprojekt',
    compareImmediate: 'Sofort',
    compareWeeks: 'Mehrere Wochen',
    comparePrivacy: 'Privatsphäre',
    compareHigh: 'Hoch',
    compareMedium: 'Mittel',
    compareLow: 'Niedrig',
    compareFlex: 'Flexibilität',
    compareRelocatable: 'Umstellbar',
    compareFixedRoom: 'Fester Raum',
    compareIndividual: 'Nur individuell',
    compareFixedLayout: 'Fester Grundriss',
    compareDisruption: 'Störung im Büro',
    frictionInstallTitle: 'Installation',
    frictionInstallDesc: 'In Stunden installiert, ohne Bauarbeiten.',
    frictionWarrantyTitle: 'Garantie',
    frictionWarrantyDesc: 'Abdeckung und lokaler Service inklusive.',
    frictionDeliveryTitle: 'Lieferung',
    frictionDeliveryDesc: 'Klare Lieferzeiten vor Freigabe der Bestellung.',
    frictionFinanceTitle: 'Finanzierung',
    frictionFinanceDesc: 'Leasingoptionen für monatliche Budgets.',
    proofOpenTitle: 'Offene Teamfläche',
    proofOpenResult: '3 Matterhorn-Kabinen verlagerten Call-Lärm weg von den Schreibtischen.',
    proofStudioTitle: 'Kundenorientiertes Studio',
    proofStudioResult: 'Kilimanjaro gab Managern einen privaten Raum ohne Bauwartezeit.',
    proofOpsTitle: 'Wachsendes Operations-Büro',
    proofOpsResult: 'Everest schuf einen festen Video-Call-Raum nahe am Team.',
    customizedBoothAlt: 'Vorschau der konfigurierten Kabine',
    monFri96: 'Mo-Fr 9-18 Uhr',
    monFri107: 'Mo-Fr 10-19 Uhr',
  },
  hu: {
    navProducts: 'Termékek',
    navSound: 'Hangdemó',
    navCustomization: 'Testreszabás',
    navShowroom: 'Bemutatóterem',
    navContact: 'Kapcsolat',
    navQuote: 'Ajánlat',
    heroTitle: 'Tér a fókuszhoz.',
    heroBody:
      'Privát akusztikus kabinok, amelyek a nyitott irodát csendes, koncentrált térré alakítják.',
    requestQuote: 'Ajánlatkérés',
    exploreModels: 'Modellek',
    trustedBy: 'Növekvő csapatok választása',
    stickyShowroom: 'Showroom foglalás',
    quoteTitle: 'Ajánlatkérés',
    quoteDescription: 'Kabinajánlás és árirány 24 órán belül.',
    quotePanelTitle: 'Tervezzünk csendesebb irodát.',
    quotePanelBody:
      'Küldj pár adatot, és javaslunk megfelelő méretet, darabszámot és következő lépést.',
    quoteBenefitPrice: 'Árirány 24 órán belül',
    quoteBenefitAssessment: 'Ingyenes irodai zajfelmérés',
    quoteBenefitSlots: 'Showroom időpontok ezen a héten',
    quoteBenefitLeasing: 'Lízing opciók elérhetők',
    name: 'Név',
    company: 'Cég',
    email: 'E-mail',
    phone: 'Telefon',
    city: 'Város',
    boothNeed: 'Kabin igény',
    notesPlaceholder: 'Mit érdemes tudnunk az irodáról?',
    sendRequest: 'Küldés',
    notSure: 'Még nem biztos',
    multipleBooths: 'Több kabin',
    productsTitle: 'Válaszd ki a tered.',
    productsBody:
      'Egyéni fókusztól a csapatmeetingig: megoldás minden privát irodai helyzetre.',
    getPrice: 'Ár 24 órán belül',
    soundTitle: 'Hallgasd meg a különbséget.',
    soundBody: 'Válts a nyitott iroda és a Silent Box kabin között.',
    soundHint: 'Kattints a valódi hangösszehasonlításhoz.',
    openDoor: 'Nyitott ajtó 85 dB',
    closedDoor: 'Zárt ajtó 30 dB',
    stopSound: 'Hang leállítása',
    openDoorLabel: 'Nyitott ajtó',
    closedDoorLabel: 'Zárt ajtó',
    office85: 'Az irodai zaj eléri a 85 dB-t',
    silent30: 'A Silent Box 30 dB-re csökkenti',
    noisyDesc:
      'Beszélgetések, billentyűzetek, telefonok és háttérzene zavaró környezetet teremtenek.',
    silentDesc: 'A precíz akusztikai panelek könyvtári csendhez közeli szintre csökkentik a zajt.',
    showroomDemo: 'Valódi showroom demó',
    hearShowroom: 'Hallgasd meg a bemutatóteremben.',
    bringDemo:
      'Hozd a saját hívásod, laptopod vagy kollégád, és hasonlítsd össze élőben.',
    bookSoundDemo: 'Hangdemó foglalása',
    planFaster: 'Gyorsabb tervezés',
    salesTitle: 'Találd meg a megfelelő kabint, mielőtt értékesítővel beszélsz.',
    freeAssessment: 'Ingyenes irodai zajfelmérés',
    findBooth: 'Kabin választó',
    recommendedFor: 'Ajánlott ehhez',
    employeeCalculator: 'Létszám kalkulátor',
    employeeQuestion: 'Hány munkatárs használja az irodát?',
    startingPlan: 'Kezdő javaslat',
    finalQuantity: 'A végső darabszám a meetingektől, alaprajztól és hibrid munkától függ.',
    compareOptions: 'Opciók összehasonlítása',
    compareBody: 'A Silent Box privát teret ad felújítás nélkül.',
    lowerFriction: 'Könnyebb döntés',
    buyerResources: 'Vásárlói anyagok',
    buyerTitle: 'Kérd a vásárlói útmutatót és specifikációt.',
    buyerBody: 'Hasznos facility managereknek, építészeknek és összehasonlító csapatoknak.',
    getSpecSheet: 'Specifikáció kérése',
    architectPack: 'Építész csomag',
    showroomTitle: 'Tapasztald meg a csendet élőben.',
    showroomBody: 'Látogass el bemutatótermünkbe, és halld a különbséget saját füllel.',
    bookVisit: 'Látogatás foglalása',
    virtualTitle: 'Nem tudsz személyesen jönni?',
    virtualBody: 'Foglalj online konzultációt tértervező szakértőinkkel.',
    virtualTour: 'Online túra foglalása',
    finalTitle: 'Hozzunk létre csendesebb munkahelyeket.',
    finalBody: 'Alakítsd az irodát fókuszáltabb, privátabb és produktívabb térré.',
    getStarted: 'Kezdés',
    downloadBrochure: 'Brosúra letöltése',
    productMatterhornTagline: 'Személyes fókuszkabin',
    productKilimanjaroTagline: 'Privát együttműködési tér',
    productEverestTagline: 'Kompakt csapatmeeting szoba',
    priceMatterhorn: '€6 999-tól',
    priceKilimanjaro: '€9 999-tól',
    priceEverest: '€14 999-tól',
    productMatterhornFeature1: 'Telefonfülke méretű alapterület',
    productMatterhornFeature2: 'Ideális hívásokhoz',
    productMatterhornFeature3: 'Egyéni fókuszmunka',
    productKilimanjaroFeature1: 'Kétszemélyes meetingek',
    productKilimanjaroFeature2: 'Videóhívások',
    productKilimanjaroFeature3: 'Diszkrét interjúk',
    productEverestFeature1: 'Csapatmeetingek',
    productEverestFeature2: 'Ügyfélprezentációk',
    productEverestFeature3: 'Kiscsoportos egyeztetések',
    problemTitle: 'A zaj valódi ára.',
    problemBody:
      'A nyitott iroda segíti a kapcsolódást, de törékennyé teszi a fókuszt. A hívások kiszűrődnek az asztalokhoz, a tárgyalók foglaltak, és minden megszakítás időbe kerül.',
    problemBusyAlt: 'Zajos nyitott iroda',
    problemSilentAlt: 'Silent Box akusztikus kabin',
    problemStat1: 'gyakori figyelemelterelésről számol be',
    problemStat2: 'nem talál elég privát meetingteret',
    problemStat3: 'kell a fókusz visszanyeréséhez megszakítás után',
    customerFitTitle: 'Minden döntéshozónak érthető érték.',
    customerFitBody:
      'Minden csapat más okból vásárol csendet. Az Atlasz Silent Boxes közös, gyakorlatias választ ad facilitynek, pénzügynek, HR-nek és a napi felhasználóknak.',
    cfFacilityTitle: 'Facility managerek',
    cfFacilityNeed: 'Adj privát kapacitást építkezés nélkül.',
    cfFacilityProof: 'Moduláris telepítés, tervezhető alapterület, szervizelhető komponensek.',
    cfHrTitle: 'HR és people csapatok',
    cfHrNeed: 'Nyugodtabb közös irodát teremts kevesebb zavaró tényezővel.',
    cfHrProof: 'Privát hívások, visszavonuló terek, fókuszzónák és neurodiverz-barát használat.',
    cfFinanceTitle: 'Pénzügy és vezetőség',
    cfFinanceNeed: 'Mérhető alternatíva új tárgyalók építése helyett.',
    cfFinanceProof: 'Kevesebb fennakadás, skálázható bevezetés és tisztább kihasználtság.',
    cfLegalTitle: 'Jogi, egészségügyi és tanácsadói csapatok',
    cfLegalNeed: 'Védd a bizalmas beszélgetéseket megosztott munkaterekben.',
    cfLegalProof: 'Akusztikai csökkentés, vizuális privát opciók és biztonságos meetinghelyzetek.',
    cfTeamsTitle: 'Csapatok és operáció',
    cfTeamsNeed: 'Megbízható terek hívásokhoz, interjúkhoz, deep workhöz és gyors egyeztetésekhez.',
    cfTeamsProof: 'A Matterhorn, Kilimanjaro és Everest méretek lefedik a napi irodai folyamatokat.',
    cfCoworkingTitle: 'Coworking irodák',
    cfCoworkingNeed: 'Adj prémium, foglalható privát teret, amit a tagok tényleg értékelnek.',
    cfCoworkingProof: 'Foglalható kabinok, tartós felületek és könnyű elhelyezés alaprajzon.',
    featureAcousticTitle: 'Akusztikai komfort',
    featureAcoustic1: 'Többrétegű hangelnyelés',
    featureAcoustic2: 'Kevesebb beszéd okozta zavarás',
    featureAcoustic3: 'Nyugodtabb belső érzet',
    featureOpsTitle: 'Üzemeltetési illeszkedés',
    featureOps1: 'Nincs nagy építkezés',
    featureOps2: 'Áthelyezhető, ha változik a csapat',
    featureOps3: 'Könnyű karbantartási hozzáférés',
    featureQualityTitle: 'Munkahelyi minőség',
    featureQuality1: 'Szellőzés és világítás',
    featureQuality2: 'Áram a fókuszált munkához',
    featureQuality3: 'Anyagok prémium irodákhoz',
    useCasesTitle: 'Mindennapi okok, amikor kell egy kabin.',
    useCasesBody: 'Egy termék sok apró irodai súrlódást old meg.',
    useCase1: 'Privát értékesítési hívások',
    useCase2: 'Toborzási interjúk',
    useCase3: 'Terápiás vagy konzultációs hívások',
    useCase4: 'Jogi és pénzügyi egyeztetések',
    useCase5: 'Deep work sprintek',
    useCase6: 'Podcast vagy webinar felvétel',
    useCase7: 'Hibrid csapatmeetingek',
    useCase8: 'Rövid csendes visszatöltődés',
    interactiveTitle: 'Teljesítményre tervezve.',
    interactiveBody: 'Fedezd fel azokat a részleteket, amelyek a kabint kényelmessé, csendessé és könnyen használhatóvá teszik.',
    hotspotHint: 'Vidd az egeret a pontokra a funkciók megismeréséhez',
    hotspotVentTitle: 'Okos szellőzés',
    hotspotVentDesc: 'Friss levegő CO2-tudatos vezérléssel.',
    hotspotSoundTitle: 'Hangszigetelés',
    hotspotSoundDesc: '30 dB akusztikai csökkentés többrétegű anyagokkal.',
    hotspotLightTitle: 'LED világítás',
    hotspotLightDesc: 'Állítható színhőmérséklet hívásokhoz és fókuszmunkához.',
    hotspotSeatTitle: 'Ergonomikus ülés',
    hotspotSeatDesc: 'Kényelmes ülés hosszabb munkamenetekhez is.',
    hotspotSensorsTitle: 'Okos szenzorok',
    hotspotSensorsDesc: 'Foglaltsági és használati adatok jobb tervezéshez.',
    hotspotPowerTitle: 'Áramcsatlakozók',
    hotspotPowerDesc: 'USB-C, vezeték nélküli töltés és szabványos aljzatok.',
    hotspotEcoTitle: 'Felelős anyaghasználat',
    hotspotEcoDesc: 'Tartós felületek kisebb terhelésű anyagkombinációval.',
    customizationTitle: 'Tervezd meg a saját tered.',
    customizationBody: 'Igazítsd a kabint az iroda színvilágához, anyagelvárásaihoz és napi használatához.',
    colorLabel: 'Szín',
    materialLabel: 'Anyag',
    sizeLabel: 'Méret',
    selectedLabel: 'Kiválasztva',
    customQuote: 'Egyedi ajánlat kérése',
    yourConfiguration: 'Saját konfiguráció',
    livePreview: 'Élő előnézet',
    colorCharcoal: 'Antracit',
    colorSage: 'Zsályazöld',
    colorWarmWhite: 'Meleg fehér',
    colorWood: 'Fa',
    colorGraphite: 'Grafit',
    materialOak: 'Tölgy furnér',
    materialOakFinish: 'Természetes fa',
    materialFelt: 'Filc panel',
    materialFeltFinish: 'Akusztikus szövet',
    materialPowder: 'Porszórt felület',
    materialPowderFinish: 'Matt fém',
    materialGlass: 'Üveg',
    materialGlassFinish: 'Szatén',
    environmentTitle: 'Több iparágban bizonyított.',
    environmentBody: 'Bizalmas tanácsadástól gyorsan növekvő csapatokig: az Atlasz Silent Boxes a munkamódhoz igazodik.',
    envLawTitle: 'Ügyvédi irodák',
    envLawDesc: 'Bizalmas ügyfélhívások nyitott irodában',
    envTechTitle: 'Tech csapatok',
    envTechDesc: 'Fókuszterek pörgős termékcsapatoknak',
    envCoworkTitle: 'Coworking irodák',
    envCoworkDesc: 'Foglalható privát tér megosztott munkahelyeken',
    envHealthTitle: 'Egészségügy',
    envHealthDesc: 'Privát konzultációs terek érzékeny beszélgetésekhez',
    envEnterpriseTitle: 'Nagyvállalati irodák',
    envEnterpriseDesc: 'Skálázható privát kapacitás nagy csapatoknak és több szintre',
    envArchTitle: 'Építész stúdiók',
    envArchDesc: 'Akusztikus terek, amelyek tiszteletben tartják az enteriőrt',
    caseStudies: 'Esettanulmányok kérése',
    techTitle: 'Technika, ami csendben dolgozik.',
    techBody: 'Minden kabin akusztikai teljesítményt, kényelmi rendszereket és irodai napi használatra választott anyagokat kombinál.',
    techAcousticTitle: 'Akusztikai mérnöki munka',
    techAcousticDesc: 'Többrétegű hangelnyelés precízen gyártott panelekkel.',
    techVentTitle: 'Szellőzőrendszer',
    techVentDesc: 'Csendes légkeringetés okos szabályozással.',
    techPowerTitle: 'Áram és csatlakozás',
    techPowerDesc: 'Integrált töltés és rendezett kábelkezelés.',
    techClimateTitle: 'Klímakomfort',
    techClimateDesc: 'Stabil komfort hosszabb használat közben is.',
    techSustainTitle: 'Felelős anyagok',
    techSustainDesc: 'Kisebb terhelésű anyagok tanúsított forrásokból.',
    techAnalyticsTitle: 'Okos analitika',
    techAnalyticsDesc: 'Használati adatok jobb munkahelytervezéshez.',
    specReduction: '30 dB csökkentés',
    specAbsorption: 'Széles spektrumú hangelnyelés',
    specEcho: 'Visszhang kontroll',
    specFans: 'Csendes ventilátorok',
    specFreshAir: 'Friss levegő keringetés',
    specSensors: 'Okos szenzorok',
    specUsb: 'USB-C áram',
    specWireless: 'Vezeték nélküli töltés',
    specCable: 'Kábelátvezetések',
    specCooling: 'Aktív hűtés',
    specHeat: 'Hőelvezetés',
    specHumidity: 'Páratartalom kontroll',
    specRecycled: '80% újrahasznosított tartalom',
    specVoc: 'Alacsony VOC',
    specCarbon: 'Alacsonyabb karbon opciók',
    specOccupancy: 'Foglaltság érzékelés',
    specPatterns: 'Használati minták',
    specMaintenance: 'Karbantartási jelzések',
    statYears: 'Év K+F',
    statPatents: 'Szabadalom',
    statUptime: 'Rendelkezésre állás',
    statWarranty: 'Garancia',
    testimonialsTitle: 'Csapatok világszerte szeretik.',
    testimonialsBody: 'Az Atlasz Silent Boxes akkor kerül elő, amikor a fókusz, privát tér és gyors telepítés egyszerre számít.',
    testQuote1: 'A nyitott irodánk azonnal könnyebben használható lett. A csendes szobákat az első naptól használták.',
    testQuote2: 'Az ügyfélbizalmasság nem alku tárgya. A kabinok privát teret adtak átépítés nélkül.',
    testQuote3: 'A kabin az enteriőr része lett, nem ideiglenes irodai javításnak hat.',
    testQuote4: 'A telepítés tiszta és gyors volt. Megspóroltuk az építkezéssel járó fennakadást.',
    testQuote5: 'Végre tudok elmélyült munkát végezni anélkül, hogy szabad tárgyalót keresnék.',
    testQuote6: 'Az üzleti indoklás egyszerű volt: kevesebb megszakítás, jobb hívások, gyors bevezetés.',
    roleOps: 'Operációs vezető',
    rolePartner: 'Ügyvezető partner',
    roleDesign: 'Design vezető',
    roleFacilities: 'Facility manager',
    roleEngineer: 'Senior mérnök',
    roleCoo: 'COO',
    avgRating: 'Átlagos értékelés',
    companies: 'Cég',
    boothsInstalled: 'Telepített kabin',
    contactEmail: 'Írj nekünk',
    contactPhone: 'Hívj minket',
    contactChat: 'Élő chat',
    chatHours: 'Elérhető 9-18 között',
    footerTagline: 'Prémium akusztikus irodai megoldások.',
    footerProducts: 'Termékek',
    footerFeatures: 'Funkciók',
    footerPricing: 'Árak',
    footerCustomization: 'Testreszabás',
    footerCompany: 'Cég',
    footerAbout: 'Rólunk',
    footerCareers: 'Karrier',
    footerPress: 'Sajtó',
    footerSupport: 'Támogatás',
    footerContact: 'Kapcsolat',
    footerFaq: 'GYIK',
    footerWarranty: 'Garancia',
    footerRights: 'Minden jog fenntartva.',
    footerPrivacy: 'Adatvédelem',
    footerTerms: 'Feltételek',
    footerCookies: 'Sütik',
    soundSealed: 'zárva',
    soundLeaking: 'kiszűrődik',
    noiseReduction: 'Zajcsökkentés',
    soundAbsorption: 'Hangelnyelés',
    insideBooth: 'Kabinon belül',
    boothSoloTitle: 'Hívások és deep work',
    boothSoloDesc: 'Telefonhívásokhoz, videómeetingekhez és csendet igénylő egyéni munkához.',
    boothDuoTitle: '1:1 meetingek',
    boothDuoDesc: 'Interjúkhoz, vezetői check-inekhez, páros munkához és privát beszélgetésekhez.',
    boothMeetTitle: 'Csapathívások',
    boothMeetDesc: 'Kisebb csapatokhoz, ügyfélprezentációkhoz és rendszeres meetingekhez.',
    recSmall: '1 Matterhorn + 1 Kilimanjaro',
    recMedium: '2 Matterhorn + 1 Kilimanjaro + 1 Everest',
    recLarge: '4 Matterhorn + 2 Kilimanjaro + 2 Everest',
    recCustom: 'Egyedi többzónás terv',
    compareNeed: 'Igény',
    compareSilent: 'Silent Box',
    compareMeeting: 'Tárgyaló',
    compareHeadphones: 'Fejhallgató',
    compareRenovation: 'Felújítás',
    compareTime: 'Használatba vétel ideje',
    compareFast: 'Gyors telepítés',
    compareProject: 'Építési projekt',
    compareImmediate: 'Azonnali',
    compareWeeks: 'Hetekig tart',
    comparePrivacy: 'Privát tér',
    compareHigh: 'Magas',
    compareMedium: 'Közepes',
    compareLow: 'Alacsony',
    compareFlex: 'Rugalmasság',
    compareRelocatable: 'Áthelyezhető',
    compareFixedRoom: 'Fix helyiség',
    compareIndividual: 'Csak egyéni',
    compareFixedLayout: 'Fix alaprajz',
    compareDisruption: 'Irodai fennakadás',
    frictionInstallTitle: 'Telepítés',
    frictionInstallDesc: 'Órák alatt telepíthető, építkezés nélkül.',
    frictionWarrantyTitle: 'Garancia',
    frictionWarrantyDesc: 'Garanciális háttér és helyi szerviz támogatás.',
    frictionDeliveryTitle: 'Szállítás',
    frictionDeliveryDesc: 'Egyértelmű átfutási idők jóváhagyás előtt.',
    frictionFinanceTitle: 'Finanszírozás',
    frictionFinanceDesc: 'Lízing opciók havi költségkerethez.',
    proofOpenTitle: 'Nyitott csapatmunka tér',
    proofOpenResult: '3 Matterhorn kabin elvitte a hívászajt a fő asztalterületről.',
    proofStudioTitle: 'Ügyfélközpontú stúdió',
    proofStudioResult: 'A Kilimanjaro privát vezetői teret adott építési várakozás nélkül.',
    proofOpsTitle: 'Növekvő operációs iroda',
    proofOpsResult: 'Az Everest dedikált videóhívás-teret hozott létre a csapat mellett.',
    customizedBoothAlt: 'Testreszabott kabin előnézete',
    monFri96: 'H-P 9-18',
    monFri107: 'H-P 10-19',
  },
} satisfies Record<Language, Record<string, string>>;

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
  labels: typeof labels;
  languageNames: typeof languageNames;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      labels,
      languageNames,
      t: (key: string) => translations[language][key] ?? translations.en[key] ?? key,
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used inside LanguageProvider');
  }

  return context;
}

export type TranslationKey = keyof typeof translations.en;
